// The following code could be generated by a tool

// Include this file in .hxx before Owner declaration

#pragma once

class Fsm : public FsmBase
{
public:
    static const Fsm::State kOff;
    static const Fsm::State kOn;
    static const Fsm::State kGreen;
    static const Fsm::State kYellow;
    static const Fsm::State kRed;
    static const Fsm::State kRedYellow;

    static const Fsm::Transition kYellowRedTransition;
};
