// The following code could be generated by a tool

#pragma once

// State Off
void FsmOffEntry(Fsm::StatePtr state);
Fsm::Transition FsmOffHandler(Fsm::StatePtr state, Fsm::Event event);
void FsmOffExit(Fsm::StatePtr state);

// State On
void FsmOnEntry(Fsm::StatePtr state);
Fsm::Transition FsmOnHandler(Fsm::StatePtr state, Fsm::Event event);
void FsmOnExit(Fsm::StatePtr state);

// State Green
Fsm::Transition FsmGreenHandler(Fsm::StatePtr state, Fsm::Event event);

// State Yellow
Fsm::Transition FsmYellowHandler(Fsm::StatePtr state, Fsm::Event event);

// State Red
Fsm::Transition FsmRedHandler(Fsm::StatePtr state, Fsm::Event event);

// State RedYellow
Fsm::Transition FsmRedYellowHandler(Fsm::StatePtr state, Fsm::Event event);

// Action Transitions
void FsmYellowRedTransitionAction();
